config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  resources :messages

  resources :properties
  get '/my_properties', to: 'properties#my_properties'
  root 'properties#index'

  get '/signup', to: 'users#new'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/help', to: 'pages#help'
  get '/help/owner', to: 'pages#owner_help', as: 'owner_help'
  get '/help/guest', to: 'pages#guest_help', as: 'guest_help'

  resources :bookings
  get '/bookings/:id/edit_status', to: 'bookings#edit_status', as: 'edit_status'
  patch '/bookings/:id/update_status',
        to: 'bookings#update_status',
        as: 'update_status'
  patch '/bookings/:id/approve', to: 'bookings#approve', as: 'approve'
  patch '/bookings/:id/decline', to: 'bookings#decline', as: 'decline'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :images

  @countries = Country.pluck(:name)
  @cities = City.pluck(:name)

  validates :name, presence: true
  validates :category, presence: true
  validates :city,
            presence: true,
            inclusion: {
              in: @cities,
              message: '%{value} is not a valid city name',
            }
  validates :country,
            presence: true,
            inclusion: {
              in: @countries,
              message: '%{value} is not a valid country name',
            }

  def self.ransackable_attributes(auth_object = nil)
    %w[city country facilities name neighbourhood rating]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[bookings images_attachments images_blobs user]
  end

  def rating
    self.reviews.average(:rating).round(2)
  end

  def has_reviews?
    self.reviews.count > 0
  end

  def reviews_count
    self.reviews.count
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :require_owner, only: %i[new create my_properties]
  before_action :set_countries, only: %i[new create]
  before_action :set_cities, only: %i[new create]

  def index
    @q = Property.ransack(params[:q])
    @pagy, @properties =
      pagy(@q.result(distinct: true).order(created_at: :desc), items: 20)
  end

  def my_properties
    @pagy, @properties = pagy(current_user.properties.order(created_at: :desc))
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
    @countries = Country.pluck(:name)
    @cities = City.pluck(:name)
  end

  def create
    @property = Property.create(property_params)
    @property.images.attach(params[:property][:images])

    if @property.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @property = Property.find(params[:id])
    @countries = Country.pluck(:name)
    @cities = City.pluck(:name)
  end

  def update
    @property = Property.find(params[:id])
    @property.images.attach(params[:property][:images])
    if @property.update(property_params)
      redirect_to @property
    else
      render 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    flash[:success] = 'The property was successfully destroyed.'
    redirect_to root_url
  end

  private

  def property_params
    params
      .require(:property)
      .permit(
        :user_id,
        :category,
        :country,
        :city,
        :neighbourhood,
        :name,
        :description,
        :facilities,
        :guests,
        :bedrooms,
        :beds,
        :baths,
        :price,
        :currency,
        :images,
      )
      .merge(user: current_user, is_available: true)
  end

  def set_countries
    @countries = Country.pluck(:name)
  end

  def set_cities
    @cities = City.pluck(:name)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_button.html.erb
<div class="block rounded-lg p-4 shadow-sm shadow-indigo-100">
  <div class="mt-2">
    <div>
      <%= link_to link_text,
          path,
          class:
            "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" %>
    </div>
  </div>
</div>

app/views/properties/_card.html.erb
<div class="h-104 rounded overflow-hidden shadow-lg">
  <%= link_to(p) do %>
    <%= image_tag define_image_url(p), class: "h-56 w-full" %>
  <% end %>
  <div class="px-6 py-4">
    <%= link_to(p) do %>
      <div class="font-bold text-xl mb-2"><%= p.name %></div>
      <div class="font-bold text-l mb-2"><%= p.city %>,
        <%= p.country %></div>
    <% end %>
    <p class="text-gray-700 text-base"><%= p.description %></p>
  </div>

  <div class="px-6 py-4">
    <% if p.has_reviews? %>
      <%= link_to reviews_path(property_id: p.id) do %>
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-yellow-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        ><title>Rating star</title><path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          ></path></svg>
        <p class="ml-2 mr-2 text-sm font-bold text-gray-900 dark:text-white"><%= p.rating %></p>
        <span class="text-sm font-medium text-gray-900 dark:text-white"><%= p.reviews_count %>
          reviews</span>
      <% end %>
    <% else %>
      <span class="text-sm font-medium text-gray-900 dark:text-white">No reviews available</span>
    <% end %>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with model: @property do |f| %>
  <div class="mb-6">
    <%= f.file_field :images,
                 multiple: true,
                 class:
                   "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.text_field :category,
                 placeholder: 'Category',
                 class:
                   "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6 flex-right">
    <%= f.select :country,
             @countries,
             class:
               "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    <%= f.select :city,
             @cities,
             class:
               "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= f.text_field :neighbourhood,
                 placeholder: 'Neighbourhood',
                 class:
                   "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= f.text_field :name,
                 placeholder: "Name",
                 class:
                   "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= f.text_field :description,
                 placeholder: "Description",
                 class:
                   "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.text_area :facilities,
                placeholder: "Facilities",
                rows: "4",
                class:
                  "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.number_field :guests,
                   placeholder: "Number of accepted guests",
                   class:
                     "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.number_field :bedrooms,
                   placeholder: "Number of bedrooms",
                   class:
                     "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.number_field :beds,
                   placeholder: "Number of beds",
                   class:
                     "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.number_field :baths,
                   placeholder: "Number of bathrooms",
                   class:
                     "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.number_field :price,
                   placeholder: "Price per night",
                   class:
                     "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-6">
    <%= f.text_field :currency,
                 placeholder: "Currency",
                 class:
                   "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <%= f.submit "Submit",
           class:
             "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  <%= link_to "Cancel",
  @property,
  class:
    "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
<% end %>

app/views/properties/_property.html.erb
<div class="h-104 rounded overflow-hidden shadow-lg">
  <%= link_to(property) do %>
    <%= image_tag define_image_url(property), class: "h-56 w-full" %>
  <% end %>
  <div class="px-6 py-4">
    <%= link_to(property) do %>
      <div class="font-bold text-xl mb-2"><%= property.name %></div>
      <div class="font-bold text-l mb-2"><%= property.city %>,
        <%= property.country %></div>
    <% end %>
    <p class="text-gray-700 text-base"><%= property.description %></p>
  </div>

  <div class="px-6 py-4">
    <% if property.has_reviews? %>
      <%= link_to reviews_path(property_id: property.id) do %>
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-yellow-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        ><title>Rating star</title><path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          ></path></svg>
        <p class="ml-2 mr-2 text-sm font-bold text-gray-900 dark:text-white"><%= property.rating %></p>
        <span class="text-sm font-medium text-gray-900 dark:text-white"><%= property.reviews_count %>
          reviews</span>
      <% end %>
    <% else %>
      <span class="text-sm font-medium text-gray-900 dark:text-white">No reviews available</span>
    <% end %>
  </div>
</div>

app/views/properties/edit.html.erb
<%= render 'partials/section_title', title: 'Edit property' %>
<div class="mt-10 sm:mt-0 text-black">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<div
  class="
    p-10
    grid
    grid-cols-1
    sm:grid-cols-1
    md:grid-cols-4
    lg:grid-cols-4
    xl:grid-cols-4
    gap-5
  "
>
  <%= render @properties %>
</div>

<%= render("partials/pagination") %>

app/views/properties/my_properties.html.erb
<div
  class="
    p-10
    grid
    grid-cols-1
    sm:grid-cols-1
    md:grid-cols-4
    lg:grid-cols-4
    xl:grid-cols-4
    gap-5
  "
>
  <% @properties.each do |p| %>
    <%= render "property", property: p %>
  <% end %>
</div>

<%= render("partials/pagination") %>

app/views/properties/new.html.erb
<%= render 'partials/validation_errors', model: @property %>

<%= render "form" %>

app/views/properties/show.html.erb
<div class="block rounded-lg p-4 shadow-sm shadow-indigo-100">
  <div class="mt-2">
    <dl>
      <div>
        <dt class="sr-only">Price</dt>

        <dd class="text-sm text-gray-500">$<%= @property.price %>,00 / night</dd>
      </div>

      <div>
        <dt class="sr-only">Address</dt>

        <dd class="font-medium"><%= @property.city %>,
          <%= @property.country %></dd>
      </div>
    </dl>

    <div class="mt-6 flex items-center gap-8 text-xs">
      <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">

        <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">

          <div class="mt-1.5 sm:mt-0">
            <p class="text-gray-500"><%= @property.baths %>
              Bathrooms</p>
          </div>
        </div>

        <div class="sm:inline-flex sm:shrink-0 sm:items-center sm:gap-2">

          <div class="mt-1.5 sm:mt-0">
            <p class="text-gray-500"><%= @property.bedrooms %>
              Bedrooms</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @property.images.attached? %>
    <% @property.images.each do |i| %>
      <%= image_tag i, class: "h-auto w-full rounded-md object-cove mt-5" %>
    <% end %>
  <% else %>
    <%= image_tag define_image_url(@property)%>
  <% end %>

  <% if current_user %>
    <% if current_user.guest? %>
      <%= render 'button', link_text: 'Reserve', path: new_booking_path(property_id: @property.id) %>
    <% end %>

    <% if @property.user_id == current_user.id %>
      <div class="block rounded-lg p-4 shadow-sm shadow-indigo-100">
        <div class="mt-2">
          <div class="flex">
            <%= link_to "Show booking requests",
          bookings_path(property_id: @property.id),
          class:
            "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" %>
            <%= link_to "Edit",
          edit_property_path(@property.id),
          class:
            "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" %>
            <%= button_to "Delete",
          property_path(@property),
          method: :delete,
          class:
            "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
          </div>

        </div>
      </div>

    <% end %>
  <% else %>
    <%= render 'button', link_text: 'Click here to login if you want to book a property', path: login_path %>
  <% end %>