config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  resources :messages

  resources :properties
  get '/my_properties', to: 'properties#my_properties'
  root 'properties#index'

  get '/signup', to: 'users#new'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/help', to: 'pages#help'
  get '/help/owner', to: 'pages#owner_help', as: 'owner_help'
  get '/help/guest', to: 'pages#guest_help', as: 'guest_help'

  resources :bookings
  get '/bookings/:id/edit_status', to: 'bookings#edit_status', as: 'edit_status'
  patch '/bookings/:id/update_status',
        to: 'bookings#update_status',
        as: 'update_status'
  patch '/bookings/:id/approve', to: 'bookings#approve', as: 'approve'
  patch '/bookings/:id/decline', to: 'bookings#decline', as: 'decline'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  belongs_to :guest, class_name: 'User'
  belongs_to :property

  validates :status,
            presence: true,
            inclusion: {
              in: %w[pending approved declined],
              message: '%{value} is not a valid booking status',
            }

  validates :guests_count, :start_at, :end_at, presence: true

  validate :validate_checkout_after_checkin

  validate :validate_checkin_olther_than_today

  def has_comment?
    self.comment != nil
  end

  private

  def validate_checkout_after_checkin
    return if end_at.blank? || start_at.blank?

    if end_at < start_at
      errors.add(:end_at, '- Checkout date must be greater than check-in date')
    end
  end

  def validate_checkin_olther_than_today
    return if end_at.blank? || start_at.blank?

    if start_at < Date.today
      errors.add(:start_at, '- Check-in date must be in future')
    end
  end
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :images

  @countries = Country.pluck(:name)
  @cities = City.pluck(:name)

  validates :name, presence: true
  validates :category, presence: true
  validates :city,
            presence: true,
            inclusion: {
              in: @cities,
              message: '%{value} is not a valid city name',
            }
  validates :country,
            presence: true,
            inclusion: {
              in: @countries,
              message: '%{value} is not a valid country name',
            }

  def self.ransackable_attributes(auth_object = nil)
    %w[city country facilities name neighbourhood rating]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[bookings images_attachments images_blobs user]
  end

  def rating
    self.reviews.average(:rating).round(2)
  end

  def has_reviews?
    self.reviews.count > 0
  end

  def reviews_count
    self.reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :property
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :properties
  has_many :owner_bookings, class_name: 'Booking', foreign_key: 'owner_id'
  has_many :guest_bookings, class_name: 'Booking', foreign_key: 'guest_id'
  has_many :messages
  has_many :reviews

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /^(.+)@(.+)$/,
              message: 'Email invalid',
              multiline: true,
            },
            length: {
              minimum: 4,
              maximum: 254,
            }
  validates :password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :role, presence: true

  def owner?
    self.role == 'owner'
  end

  def guest?
    self.role == 'guest'
  end

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def help
  end

  def owner_help
  end

  def guest_help
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]

  def index
    q = request.query_parameters
    @reviews = Review.where(property_id: q[:property_id])
    @property = Property.find(q[:property_id])
  end

  def show
  end

  def new
    @review = Review.new
    q = request.query_parameters
    @booking = Booking.find(q[:booking_id])
    @property = @booking.property
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @booking = @review.property.bookings.where(guest_id: current_user.id).first
    @property = @booking.property

    respond_to do |format|
      if @review.save
        @booking.is_reviewed = true
        @booking.save

        format.html do
          redirect_to review_url(@review),
                      notice: 'Review was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html do
          redirect_to review_url(@review),
                      notice: 'Review was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy

    respond_to do |format|
      format.html do
        redirect_to reviews_url, notice: 'Review was successfully destroyed.'
      end
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :message, :property_id, :user_id)
  end

  def booking_id_condition
    ['booking_id = ?', params[:booking_id]] unless params[:booking_id].blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :role,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  DEFAULT_IMAGE_URL =
    'https://img.freepik.com/free-photo/modern-living-room-style_53876-144814.jpg?w=1380&t=st=1679986771~exp=1679987371~hmac=8f503fc971412595ec3a4b7508c2ca8228137bcc8a11ed170d602519fecb6a12'

  def define_image_url(model)
    model.images.attached? ? model.images.first : DEFAULT_IMAGE_URL
  end

  def pages_titles
    %w[Home About Contact Help]
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def current_user_owns_property(booking)
    current_user.id == booking.owner_id
  end

  def link_text
    if current_user.owner?
      'Approve or Decline'
    elsif current_user.guest?
      'Edit'
    end
  end

  def link_path(booking)
    if link_text == 'Approve or Decline'
      booking.id.to_s + '/edit_status'
    elsif link_text == 'Edit'
      booking.id.to_s + '/edit'
    end
  end

  def display_image(booking)
  end

  def belongs_to_current_user(booking)
    current_user.id == booking.guest_id
  end

  def is_current_or_past_booking(booking)
    @today = Date.today
    booking.end_at < @today ||
      booking.start_at <= @today && booking.end_at > @today
  end

  def reviewable(booking)
    booking.is_reviewed == false && booking.status == 'approved' &&
      belongs_to_current_user(booking) && is_current_or_past_booking(booking)
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentalz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application",
    "https://unpkg.com/flowbite@1.5.1/dist/flowbite.min.css" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "partials/navbar" %>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="bg-white dark:bg-gray-900">
  <div
    class="
      gap-16
      items-center
      py-8
      px-4
      mx-auto
      max-w-screen-xl
      lg:grid
      lg:grid-cols-2
      lg:py-16
      lg:px-6
    "
  >
    <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
      <h2
        class="
          mb-4
          text-4xl
          tracking-tight
          font-extrabold
          text-gray-900
          dark:text-white
        "
      >One of a kind stays and amazing travel experiences</h2>
      <p class="mb-4">Whether there are hotel rooms, villas or apartments, hosts are happy to share their places.</p>
    </div>
    <div class="grid grid-cols-2 gap-4 mt-8">
      <%= image_tag "about_us_apartment", class: "w-full rounded-lg" %>
      <%= image_tag "about_us_house", class: "mt-4 w-full lg:mt-10 rounded-lg" %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="bg-white dark:bg-gray-900">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    <h2
      class="
        mb-4
        text-4xl
        tracking-tight
        font-extrabold
        text-center
        text-gray-900
        dark:text-white
      "
    >Contact Us</h2>
    <p
      class="
        mb-8
        lg:mb-16
        font-light
        text-center
        text-gray-500
        dark:text-gray-400
        sm:text-xl
      "
    >Got a technical issue? Want to send feedback about a beta feature? Need
      details about our Business plan? Let us know.</p>
    <form action="#" class="space-y-8">
      <div>
        <label
          for="email"
          class="
            block
            mb-2
            text-sm
            font-medium
            text-gray-900
            dark:text-gray-300
          "
        >Your email</label>
        <input
          type="email"
          id="email"
          class="
            shadow-sm
            bg-gray-50
            border
            border-gray-300
            text-gray-900
            text-sm
            rounded-lg
            focus:ring-primary-500
            focus:border-primary-500
            block
            w-full
            p-2.5
            dark:bg-gray-700
            dark:border-gray-600
            dark:placeholder-gray-400
            dark:text-white
            dark:focus:ring-primary-500
            dark:focus:border-primary-500
            dark:shadow-sm-light
          "
          placeholder="name@rentalz.com"
          required
        >
        </div>
        <div>
          <label
          for="subject"
          class="
            block
            mb-2
            text-sm
            font-medium
            text-gray-900
            dark:text-gray-300
          "
        >Subject</label>
          <input
          type="text"
          id="subject"
          class="
            block
            p-3
            w-full
            text-sm
            text-gray-900
            bg-gray-50
            rounded-lg
            border
            border-gray-300
            shadow-sm
            focus:ring-primary-500
            focus:border-primary-500
            dark:bg-gray-700
            dark:border-gray-600
            dark:placeholder-gray-400
            dark:text-white
            dark:focus:ring-primary-500
            dark:focus:border-primary-500
            dark:shadow-sm-light
          "
          placeholder="Let us know how we can help you"
          required
        >
          </div>
          <div class="sm:col-span-2">
            <label
          for="message"
          class="
            block
            mb-2
            text-sm
            font-medium
            text-gray-900
            dark:text-gray-400
          "
        >Your message</label>
            <textarea
          id="message"
          rows="6"
          class="
            block
            p-2.5
            w-full
            text-sm
            text-gray-900
            bg-gray-50
            rounded-lg
            shadow-sm
            border
            border-gray-300
            focus:ring-primary-500
            focus:border-primary-500
            dark:bg-gray-700
            dark:border-gray-600
            dark:placeholder-gray-400
            dark:text-white
            dark:focus:ring-primary-500
            dark:focus:border-primary-500
          "
          placeholder="Leave a comment..."
        ></textarea>
          </div>
          <div class="flex justify-center space-x-2">
            <button
          type="button"
          data-te-ripple-init
          data-te-ripple-color="light"
          class="
            inline-block
            rounded
            bg-primary
            px-6
            pt-2.5
            pb-2
            text-xs
            font-medium
            uppercase
            leading-normal
            text-black
            shadow-[0_4px_9px_-4px_#3b71ca]
            transition
            duration-150
            ease-in-out
            hover:bg-primary-600
            hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
            focus:bg-primary-600
            focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
            focus:outline-none
            focus:ring-0
            active:bg-primary-700
            active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          "
        >
              Send message
            </button>
          </div>
        </form>
      </div>
    </div>

app/views/pages/guest_help.html.erb
<div class="bg-white dark:bg-gray-900">
  <div
    class="
      gap-16
      items-center
      py-8
      px-4
      mx-auto
      max-w-screen-xl
      lg:grid
      lg:grid-cols-2
      lg:py-16
      lg:px-6
    "
  >
    <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
      <h2
        class="
          mb-4
          text-4xl
          tracking-tight
          font-extrabold
          text-gray-900
          dark:text-white
        "
      >Steps to book a property</h2>
      <ul>
        <li class="mb-4">1. signup as guest</li>
        <li class="mb-4">2. Browse our vast collection of properties</li>
        <li class="mb-4">3. Click on rerserve buton</li>
        <li class="mb-4">4. Complete the reservation form and submit the booking request</li>
        <li class="mb-4">5. verify your My bookings section and check if your request was
          approved or declined</li>
        <li class="mb-4">6. If your booking request was approved wait until the checkin day
          and just enjoy</li>
        <li class="mb-4">7. If your booking request was declined, most likely the host
          provided a reason. Learn form that reason and improve your next
          request.</li>
        <li class="mb-4">8. After your first stay don't forget to add a review. Check "My
          bookings section", look for your recent stay and click on add
          review button. Add your rating and leave a message.</li>
      </ul>
      <p class="mb-4">If this guide is no helpful enough click
        <%= link_to contact_path do %>
          <span class="font-semibold">here</span>
        <% end %>
        to send us a message and we will get back to you as soon as possible.</p>
    </div>
    <div class="grid grid-cols-2 gap-4 mt-8">
      <%= image_tag "https://www.travelandleisure.com/thmb/CGvCEwk2MXAxkQyfRZiP01gvHvQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/airbnb-guests-NYECRACKDOWN1121-5697dad132a246548c04be8ea9b3b91c.jpg", class: "w-full rounded-lg" %>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<section class="bg-white dark:bg-gray-900">
  <div
    class="
      gap-16
      items-center
      py-8
      px-4
      mx-auto
      max-w-screen-xl
      lg:grid
      lg:grid-cols-2
      lg:py-16
      lg:px-6
    "
  >
    <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
      <h2
        class="
          mb-4
          text-4xl
          tracking-tight
          font-extrabold
          text-gray-900
          dark:text-white
          text-center
        "
      >Guides for getting started</h2>
    </div>
  </div>
</section>

<div
  class="
    p-10
    grid
    grid-cols-1
    sm:grid-cols-1
    md:grid-cols-4
    lg:grid-cols-4
    xl:grid-cols-4
    gap-5
  "
>
  <%= link_to owner_help_path do %>
    <div class="h-104 rounded overflow-hidden shadow-lg">
      <%= image_tag "https://empire-s3-production.bobvila.com/articles/wp-content/uploads/2022/12/iStock-1372309567-how-to-become-an-airbnb-host-woman-welcoming-guest.jpg" %>
      <div class="px-6 py-4">
        <p class="text-gray-700 text-base font-semibold">Getting started as owner</p>
      </div>
    </div>
  <% end %>
  <%= link_to guest_help_path do %>
    <div class="h-104 rounded overflow-hidden shadow-lg">
      <%= image_tag "https://www.travelandleisure.com/thmb/CGvCEwk2MXAxkQyfRZiP01gvHvQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/airbnb-guests-NYECRACKDOWN1121-5697dad132a246548c04be8ea9b3b91c.jpg" %>
      <div class="px-6 py-4">
        <p class="text-gray-700 text-base font-semibold">Getting started as guest</p>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/owner_help.html.erb
<div class="bg-white dark:bg-gray-900">
  <div
    class="
      gap-16
      items-center
      py-8
      px-4
      mx-auto
      max-w-screen-xl
      lg:grid
      lg:grid-cols-2
      lg:py-16
      lg:px-6
    "
  >
    <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
      <h2
        class="
          mb-4
          text-4xl
          tracking-tight
          font-extrabold
          text-gray-900
          dark:text-white
        "
      >Steps to add a property</h2>
      <ul>
        <li class="mb-4">1. signup as owner</li>
        <li class="mb-4">2. Click on your profile icon</li>
        <li class="mb-4">3. Click on "Add property"</li>
        <li class="mb-4">4. Complete the form and and click on the submit button</li>
        <li class="mb-4">5. Click again on your profile icon, click on "My properties" link and see all your listed properties</li>
      </ul>
      <p class="mb-4">If this guide is no helpful enough click
        <%= link_to contact_path do %>
          <span class="font-semibold">here</span>
        <% end %>
        to send us a message and we will get back to you as soon as possible.</p>
    </div>
    <div class="grid grid-cols-2 gap-4 mt-8">
      <%= image_tag "https://empire-s3-production.bobvila.com/articles/wp-content/uploads/2022/12/iStock-1372309567-how-to-become-an-airbnb-host-woman-welcoming-guest.jpg", class: "w-full rounded-lg" %>
    </div>
  </div>
</div>

app/views/partials/_booking_card.html.erb
<div class="h-104 rounded overflow-hidden shadow-lg">
  <div class="px-6 py-4">
    <% if b.property.images.attached? %>
      <%= image_tag b.property.images.first, class: "h-56 w-full" %>
    <% else %>
      <%= image_tag "apartment.jpeg" %>
    <% end %>
    <div class="font-bold text-xl mb-2">Guest:
      <%= b.guest.first_name %>
      <%= b.guest.last_name %></div>
    <p class="text-gray-700 text-base">Host:
      <%= b.owner.first_name %></p>
    <p class="text-gray-700 text-base">Check-in:
      <%= b.start_at %></p>
    <p class="text-gray-700 text-base">Checkout:
      <%= b.end_at %></p>
    <p class="text-gray-700 text-base">Guests number:
      <%= b.guests_count %></p>
    <p class="text-gray-700 text-base">Status:
      <%= b.status %></p>

    <% if current_user.id == b.guest_id && b.reviewable? %>
      <%= link_to "Add review",
      new_review_path(booking_id: b.id),
      class:
        "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" %>
    <% end %>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer
  class="
    p-4
    bg-white
    rounded-lg
    shadow
    md:flex
    md:items-center
    md:justify-between
    md:p-6
    dark:bg-gray-800
  "
>
  <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">©
    <%= Date.current.year %>
    <a
      href="https://github.com/marianDdev/ruby_on_rails_rentalz"
      class="hover:underline"
    >Rentalz</a>. All Rights Reserved.
  </span>
  <ul
    class="
      flex
      flex-wrap
      items-center
      mt-3
      text-sm
      text-gray-500
      dark:text-gray-400
      sm:mt-0
    "
  >
  <% pages_titles.each do |title| %>
     <% if title == 'Home' %>
      <%= link_to 'Home', root_path, class: "mr-4 hover:underline md:mr-6" %>
     <% else %>
      <%= link_to title, polymorphic_path(title.downcase),  class: "mr-4 hover:underline md:mr-6" %>
    <% end %>  
  <% end %>  
  </ul>
</footer>

app/views/partials/_pagination.html.erb
<div><%= pagy_nav(@pagy).html_safe %></div>

app/views/partials/_property_card.html.erb
<div class="h-104 rounded overflow-hidden shadow-lg">
  <%= link_to(p) do %>
    <% if p.images.attached? %>
      <%= image_tag p.images.first, class: "h-56 w-full" %>
    <% else %>
      <%= image_tag "https://img.freepik.com/free-photo/modern-living-room-style_53876-144814.jpg?w=1380&t=st=1679986771~exp=1679987371~hmac=8f503fc971412595ec3a4b7508c2ca8228137bcc8a11ed170d602519fecb6a12" %>
    <% end %>
  <% end %>
  <div class="px-6 py-4">
    <%= link_to(p) do %>
      <div class="font-bold text-xl mb-2"><%= p.name %></div>
      <div class="font-bold text-l mb-2"><%= p.city %>,
        <%= p.country %></div>
    <% end %>
    <p class="text-gray-700 text-base"><%= p.description %></p>
  </div>

  <div class="px-6 py-4">
    <% if p.reviews && p.reviews.count > 0 %>
      <%= link_to reviews_path(property_id: p.id) do %>
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-yellow-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        ><title>Rating star</title><path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          ></path></svg>
        <p class="ml-2 mr-2 text-sm font-bold text-gray-900 dark:text-white"><%= p.rating %></p>
        <span class="text-sm font-medium text-gray-900 dark:text-white"><%= p.reviews_count %>
          reviews</span>
      <% end %>
    <% else %>
      <span class="text-sm font-medium text-gray-900 dark:text-white">No reviews available</span>
    <% end %>
  </div>
</div>

app/views/partials/_review_card.html.erb
<div class="h-104 rounded overflow-hidden shadow-lg">
  <% if @review.property.images.attached? %>
    <%= image_tag @review.property.images.first, class: "h-56 w-full" %>
  <% else %>
    <%= image_tag "https://img.freepik.com/free-photo/modern-living-room-style_53876-144814.jpg?w=1380&t=st=1679986771~exp=1679987371~hmac=8f503fc971412595ec3a4b7508c2ca8228137bcc8a11ed170d602519fecb6a12" %>
  <% end %>
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= @review.user.first_name %>,
      <%= @review.user.last_name %></div>
  </div>

  <div class="px-6 py-4 flex">
    <svg
      aria-hidden="true"
      class="w-5 h-5 text-yellow-400"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    ><title>Rating star</title><path
        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
      ></path></svg>
    <p class="ml-2 mr-2 text-sm font-bold text-gray-900 dark:text-white"><%= @review.rating %></p>
  </div>
  <div class="px-6 py-4 flex">
    <span class="text-sm font-medium text-gray-900 dark:text-white">"<%= @review.message %>"</span>
  </div>
</div>

app/views/partials/_search.html.erb
<% if @q %>
  <%= search_form_for @q, url: properties_path, class: "flex
items-center" do |f| %>
    <%= f.label "Search", class: "sr-only" %>
    <div class="relative w-full">
      <div
        class="
          absolute
          inset-y-0
          left-0
          flex
          items-center
          pl-3
          pointer-events-none
        "
      >
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-gray-500 dark:text-gray-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <%= f.search_field :name_or_city_or_country_i_cont,
                     class:
                       "bg-gray-50 border
                                      border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
                                      focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700
                                      dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
                                      dark:focus:ring-blue-500 dark:focus:border-blue-500",
                     placeholder: "Search" %>
    </div>
    <%= f.submit "Search",
             class:
               "p-2.5 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  <% end %>
<% end %>

app/views/partials/_section_title.html.erb
<section class="bg-white dark:bg-gray-900">
  <div
    class="
      gap-16
      items-center
      py-8
      px-4
      mx-auto
      max-w-screen-xl
      lg:grid
      lg:grid-cols-2
      lg:py-16
      lg:px-6
    "
  >
    <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
      <h2
        class="
          mb-4
          text-4xl
          tracking-tight
          font-extrabold
          text-gray-900
          dark:text-white
          text-center
        "
      ><%= title %></h2>
    </div>
  </div>
</section>

app/views/partials/_validation_errors.html.erb
<% if model.errors.any? %>
  <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
    <h2><%= pluralize(model.errors.count, "error") %>
      prohibited this review from being saved:</h2>

    <ul>
      <% model.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>